//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpinionMinerData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpinionRequest
    {
        public OpinionRequest()
        {
            this.Opinion = new HashSet<Opinion>();
        }
    
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public string Term { get; set; }
        public System.DateTime ToDate { get; set; }
        public int DayCycle { get; set; }
        public int Repeate { get; set; }
        public int PageCount { get; set; }
    
        public virtual ICollection<Opinion> Opinion { get; set; }
    }
}
