//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpinionMinerData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opinion
    {
        public int Id { get; set; }
        public int OpinionRequestId { get; set; }
        public Nullable<double> Result { get; set; }
        public System.DateTime Created { get; set; }
        public string Term { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int PageCount { get; set; }
    
        public virtual OpinionRequest OpinionRequest { get; set; }
    }
}
